spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

